[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/spotify-token"
  to = "/.netlify/functions/spotify-token"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sounds/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
